/*
 * generated by Xtext 2.11.0
 */
package dk.deothan.math.ide

import com.google.inject.Guice
import dk.deothan.math.MathRuntimeModule
import dk.deothan.math.MathStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MathIdeSetup extends MathStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MathRuntimeModule, new MathIdeModule))
	}
	
}
