/*
 * generated by Xtext 2.11.0
 */
package dk.deothan.math.ui.tests;

import com.google.inject.Injector;
import dk.deothan.math.ui.internal.MathActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MathUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MathActivator.getInstance().getInjector("dk.deothan.math.Math");
	}

}
