/*
 * generated by Xtext 2.11.0
 */
package dk.deothan.math.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathScopeProvider extends DelegatingScopeProvider {
}
