/*
 * generated by Xtext 2.11.0
 */
package dk.deothan.math


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MathRuntimeModule extends AbstractMathRuntimeModule {
}
