/**
 * generated by Xtext 2.11.0
 */
package dk.deothan.math.math;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.deothan.math.math.Model#getExps <em>Exps</em>}</li>
 * </ul>
 *
 * @see dk.deothan.math.math.MathPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Exps</b></em>' containment reference list.
   * The list contents are of type {@link dk.deothan.math.math.NamedExpression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exps</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exps</em>' containment reference list.
   * @see dk.deothan.math.math.MathPackage#getModel_Exps()
   * @model containment="true"
   * @generated
   */
  EList<NamedExpression> getExps();

} // Model
