/*
 * generated by Xtext 2.11.0
 */
package dk.deothan.math.ui;

import com.google.inject.Injector;
import dk.deothan.math.ui.internal.MathActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MathExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MathActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MathActivator.getInstance().getInjector(MathActivator.DK_DEOTHAN_MATH_MATH);
	}
	
}
